name: Deploy After Tests

on:
  workflow_run:
    workflows: ["Tests"] # ðŸ‘ˆ Name of Workflow A
    types: [completed]

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }} # Only on success
    runs-on: ubuntu-latest

    steps:
      - run: echo "Tests passed... Starting deployment..."
